name: flake8-check

on:
  push:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
            python-version: "3.8"

      - name: make flake8-check
        run: make lint