name: flake8-check

on:
  push:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
            python-version: "3.8"

      - name: Run poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
            poetry-version: 1.1.4

      - name: Poetry install
        run: poetry install
        
      - name: make flake8-check
        run: make lint